ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-focal"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

# overwrite the vnc_startup.sh script
COPY ./src/ubuntu/install/scrcpy/vnc_startup.sh $STARTUPDIR/vnc_startup.sh

COPY ./src/ubuntu/install/scrcpy $INST_SCRIPTS/scrcpy/
RUN bash $INST_SCRIPTS/scrcpy/install_sndcpy.sh  && rm -rf $INST_SCRIPTS/scrcpy/

COPY ./src/ubuntu/install/scrcpy/custom_sndcpy_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh

# customize the vnc server
RUN rm -f /usr/share/kasmvnc/www/index.html  # a symlink to vnc.html by default, maybe doesn't exist so -f
COPY --chown=0:0 ./src/ubuntu/install/scrcpy/www /usr/share/kasmvnc/www
# injects novnc-nofrills straight into where the regular novnc client lives
# kasmvnc hard-fixes the directory to here

# Update the desktop environment to be optimized for a single application
RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
RUN cp /usr/share/backgrounds/bg_kasm.png /usr/share/backgrounds/bg_default.png
RUN apt-get remove -y xfce4-panel


######### End Customizations ###########

RUN chown 1000:0 $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

# customization
RUN mkdir -p $HOME/.vnc && chown -R 1000:1000 $HOME/.vnc
COPY --chown=1000:1000 ./src/ubuntu/install/scrcpy/kasmvnc-template.yaml $HOME/.vnc/kasmvnc-template.yaml
#COPY --chown=1000:1000 ./src/ubuntu/install/scrcpy/www $HOME/www

USER 1000
